from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path


CUSTOM_TOOLS_DIR = Path.home() / ".agentic-kali" / "custom-tools"
UNSAFE_TERMS = (
    "credential",
    "password steal",
    "token steal",
    "phishing",
    "keylogger",
    "persistence",
    "backdoor",
    "ransomware",
    "exfiltrate",
    "destructive",
)


@dataclass(frozen=True)
class BuildRequest:
    name: str
    description: str


@dataclass(frozen=True)
class BuiltTool:
    name: str
    path: Path
    command: str


def parse_build_request(text: str) -> BuildRequest | None:
    lowered = text.lower()
    if not any(phrase in lowered for phrase in ("build", "create", "write", "make")):
        return None
    if not any(phrase in lowered for phrase in ("custom tool", "testing program", "test program", "scanner", "helper app", "helper tool")):
        return None
    name = _slug(text)
    return BuildRequest(name=name, description=text.strip())


def is_safe_build_request(request: BuildRequest) -> bool:
    text = request.description.lower()
    return not any(term in text for term in UNSAFE_TERMS)


def build_custom_tool(request: BuildRequest, output_dir: Path = CUSTOM_TOOLS_DIR) -> BuiltTool:
    tool_dir = output_dir / request.name
    tool_dir.mkdir(parents=True, exist_ok=True)
    script = tool_dir / f"{request.name}.py"
    script.write_text(_script_template(request.name, request.description), encoding="utf-8")
    readme = tool_dir / "README.md"
    readme.write_text(_readme_template(request.name, request.description, script), encoding="utf-8")
    return BuiltTool(name=request.name, path=tool_dir, command=f"python3 {script}")


def _slug(text: str) -> str:
    cleaned = re.sub(r"[^a-zA-Z0-9]+", "-", text.lower()).strip("-")
    words = [word for word in cleaned.split("-") if word not in {"build", "create", "write", "make", "a", "an", "the", "custom", "tool", "testing", "program"}]
    return "-".join(words[:5]) or "agent-kal-tool"


def _script_template(name: str, description: str) -> str:
    return f'''#!/usr/bin/env python3
"""
{name}: safe authorized-testing helper generated by Agent Kal.

Request: {description}
"""
from __future__ import annotations

import argparse
import socket
import urllib.request
from urllib.parse import urlparse


def normalize_target(target: str) -> str:
    if target.startswith(("http://", "https://")):
        return target
    return "https://" + target


def check_http(target: str) -> None:
    url = normalize_target(target)
    print(f"[+] Checking {{url}}")
    try:
        with urllib.request.urlopen(url, timeout=10) as response:
            print(f"Status: {{response.status}}")
            print("Headers:")
            for key, value in response.headers.items():
                print(f"  {{key}}: {{value}}")
    except Exception as exc:
        print(f"HTTP check failed: {{exc}}")


def resolve_host(target: str) -> None:
    host = urlparse(normalize_target(target)).hostname or target
    print(f"[+] Resolving {{host}}")
    try:
        for result in socket.getaddrinfo(host, None):
            print(result[4][0])
    except Exception as exc:
        print(f"DNS lookup failed: {{exc}}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Safe recon helper for authorized testing.")
    parser.add_argument("target", help="Authorized domain or URL")
    parser.add_argument("--http", action="store_true", help="Check HTTP status and headers")
    parser.add_argument("--dns", action="store_true", help="Resolve host addresses")
    args = parser.parse_args()

    if args.dns or not args.http:
        resolve_host(args.target)
    if args.http:
        check_http(args.target)


if __name__ == "__main__":
    main()
'''


def _readme_template(name: str, description: str, script: Path) -> str:
    return f"""# {name}

Generated by Agent Kal as a safe local helper for authorized testing.

Request:
{description}

Usage:
```bash
python3 {script} example.com --dns --http
```

This helper is for reconnaissance on systems you own or have written permission to assess.
"""
